// =============================================================================
// strings.js — i18n dictionary (en + zh, mirrored 1:1).
// =============================================================================

export const STRINGS = {
    en: {
        'login.eyebrow':   'Sign in · Backend Demo',
        'login.title':     'Merchant Console',
        'login.sub':       'Sign in to connect to the backend API. This page exercises the four core flows: Balances · Orders · Vault deposit · Ledger.',
        'login.merchant':  'Merchant code',
        'login.username':  'Username',
        'login.password':  'Password',
        'login.submit':    'Sign in →',
        'login.api':       'API',
        'login.brand.eyebrow':  'Vol.04 · Web2 + Web3 Treasury',
        'login.brand.headline.l1': 'Make',
        'login.brand.headline.l2': 'Payments',
        'login.brand.headline.em': 'Borderless.',
        'login.brand.sub': 'Multi-chain stablecoin custody, fiat on/off-ramp, double-entry ledger — built for the merchant treasury desk.',
        'login.brand.live':'Live · Local stack',
        'login.brand.seal':'TCSP · MSO · Regulated',

        'header.merchant': 'Merchant',
        'header.refresh':  'Refresh',
        'header.notif':    'Notifications',
        'header.lang':     'Language',
        'header.logout':   'Sign out',

        'nav.section.vaults':   'Asset Vaults',
        'nav.section.flow':     'Money Flow',
        'nav.section.ops':      'Operations',
        'nav.section.account':  'Account',
        'nav.overview':   'Overview',
        'nav.vault':      'Stablecoin Vault',
        'nav.fiat-vault': 'Fiat Vault',
        'nav.orders':     'Invoice Orders',
        'nav.payouts':    'Payouts',
        'nav.conversion': 'Conversion',
        'nav.ledger':     'Ledger',
        'nav.approvals':  'Approvals',
        'nav.reports':    'Report Center',
        'nav.members':    'Members',
        'nav.soon':       'Soon',
        'sidebar.backend':'Backend',

        'page.overview.eyebrow': 'OBITA · MERCHANT OVERVIEW',
        'page.overview.title':   'Treasury Overview',
        'page.overview.sub':     "A quick read on today's deposits, orders, and settlement. Every number comes straight from the backend ledger.",
        'overview.kpi.available':'Total Available',
        'overview.kpi.available.meta': 'Stablecoin total · sum of AVAILABLE across USDC + USDT.',
        'overview.kpi.pending':  'Pending In',
        'overview.kpi.pending.meta':  'On-chain deposits awaiting confirmations.',
        'overview.kpi.open':     'Open Orders',
        'overview.kpi.open.meta':     'Pending payment + paid + refunding combined.',
        'overview.kpi.settled':  'Settled (recent)',
        'overview.kpi.settled.meta':  'Of the most recent 10 orders.',
        'overview.balances.title':    'Balances · per asset',
        'overview.balances.action':   'Open Vault →',
        'overview.recent.title':      'Recent Invoice Orders',
        'overview.recent.action':     'All orders →',
        'overview.recent.empty.head': 'No orders yet',
        'overview.recent.empty.body': 'Click "+ New order" in the top right to create the first one.',

        'page.vault.eyebrow': 'TCSP · STABLECOIN VAULT',
        'page.vault.title':   'Stablecoin Vault',
        'page.vault.sub':     'Provision an on-chain receive address; the scanner picks up mock-bank credit within ~10s and lifts the balance from PENDING to AVAILABLE after 12 confirmations (~30s).',
        'vault.balances.title':  'Balances · at a glance',
        'vault.address.title':   'Address Book · receive addresses',
        'vault.address.empty':   'No addresses provisioned yet',
        'vault.address.empty.sub':'Use the form below to issue one.',
        'vault.provision.title': 'Provision Address',
        'vault.provision.chain':  'Chain',
        'vault.provision.purpose':'Purpose',
        'vault.provision.label':  'Label',
        'vault.provision.submit': 'Provision Address',
        'vault.mock.title':      'Test Deposit · simulate on-chain credit',
        'vault.mock.note.lead':  'Local-demo only.',
        'vault.mock.note':       ' Backend POST /mock-bank/credit pushes a synthetic credit to the chain adapter. The scanner detects it (~10s) → writes deposit + entries 1/2; ~30s later it reaches 12 confirmations → CREDITED + entries 3/4.',
        'vault.mock.to':         'To Address',
        'vault.mock.asset':      'Asset',
        'vault.mock.amount':     'Amount',
        'vault.mock.submit':     'Inject mock-bank credit',
        'vault.mock.toast':      'Credit injected · scanner working…',
        'vault.address.copy':    'Copy address',
        'vault.address.copied':  'Address copied to clipboard',
        'vault.address.provisioned':'Address provisioned',
        'vault.address.history': 'History',

        'wallet.history.title':       'Wallet History',
        'wallet.history.empty':       'No on-chain activity yet for this address.',
        'wallet.history.deposit.confirmed': 'Deposit credited to AVAILABLE',
        'wallet.history.row.topup':   'Top-up · on-chain',
        'wallet.history.row.settle':  'Order settle · debit',
        'wallet.history.tag.live':    'LIVE',
        'wallet.history.tag.deposit': 'DEPOSIT',
        'wallet.history.tag.settle':  'SETTLE',

        'page.orders.eyebrow': 'MSO · INVOICE ORDER',
        'page.orders.title':   'Invoice Orders',
        'page.orders.sub':     'Lifecycle: CREATED → PENDING_PAYMENT → PAID → SETTLED → REFUNDING → REFUNDED. Every transition runs through an @Idempotent backend controller and posts ledger entries.',
        'orders.new':          '+ New order',
        'orders.kpi.all':      'All Orders',
        'orders.kpi.all.meta': 'Total count',
        'orders.kpi.open':     'Open',
        'orders.kpi.open.meta':'Pending payment / paid / refunding',
        'orders.kpi.settled':  'Settled',
        'orders.kpi.settled.meta':'Reached SETTLED',
        'orders.kpi.refunds':  'Refunds',
        'orders.kpi.refunds.meta':'Refunding / refunded',
        'orders.table.title':  'Orders',
        'orders.col.order':    'Order',
        'orders.col.quote':    'Quote',
        'orders.col.settle':   'Settle',
        'orders.col.channel':  'Channel',
        'orders.col.status':   'Status',
        'orders.col.time':     'Time',
        'orders.col.actions':  'Actions',
        'orders.empty.head':   'No orders yet',
        'orders.empty.body':   'Click "+ New order" to create the first one.',
        'orders.action.markPaid': 'Mark paid',
        'orders.action.settle':   'Settle',
        'orders.action.refund':   'Refund',
        'orders.action.cancel':   'Cancel',
        'orders.toast.markPaid':  'Order marked as paid',
        'orders.toast.settle':    'Settled · ledger entries posted',
        'orders.toast.cancel':    'Order cancelled',
        'orders.toast.refund':    'Refund completed · ledger entries posted',
        'orders.modal.title':     'New Invoice Order',
        'orders.modal.no':        'Merchant Order No',
        'orders.modal.quote':     'Quote',
        'orders.modal.amount':    'Amount',
        'orders.modal.settleAsset':'Settle currency',
        'orders.modal.channel':   'Payment channel',
        'orders.modal.desc':      'Description',
        'orders.modal.desc.placeholder':'optional',
        'orders.modal.cancel':    'Cancel',
        'orders.modal.create':    'Create order',
        'orders.modal.toast':     'Order created (PENDING_PAYMENT)',
        'orders.refund.prompt':   'Refund amount',
        'orders.cancel.prompt':   'Cancel reason (optional)',
        'orders.detail.title':    'Order Detail',
        'orders.detail.section.info':   'Order Information',
        'orders.detail.section.events': 'Event Timeline',
        'orders.detail.field.id':       'Order ID',
        'orders.detail.field.no':       'Merchant Order No',
        'orders.detail.field.status':   'Status',
        'orders.detail.field.quote':    'Quote',
        'orders.detail.field.settle':   'Settle',
        'orders.detail.field.channel':  'Channel',
        'orders.detail.field.expires':  'Expires',
        'orders.detail.field.created':  'Created',
        'orders.detail.field.updated':  'Updated',
        'orders.detail.field.desc':     'Description',
        'orders.detail.action.view':    'Details',

        'page.ledger.eyebrow': 'OBITA · LEDGER SNAPSHOT',
        'page.ledger.title':   'Ledger Snapshot',
        'page.ledger.sub':     'Latest balance_after for every account. The full per-tx feed (GET /v1/accounts/{id}/entries) is on the P1 backend roadmap.',
        'ledger.section':      'Account Balances',
        'ledger.col.no':       '#',
        'ledger.col.asset':    'Asset',
        'ledger.col.type':     'Account Type',
        'ledger.col.balance':  'Current Balance',
        'ledger.col.note':     'Note',
        'ledger.row.note':     'snapshot · balance_after',
        'ledger.note.lead':    'Tip:',
        'ledger.note.body':    ' the full happy-path 8 entries are visible directly in PG: ',
        'ledger.note.body2':   ' — one deposit + order settle + refund forms 4 paired debit/credit segments. The negative PLATFORM SETTLEMENT row represents on-chain assets held in custody (see 03-DOMAIN_MODEL.md §4).',

        'soon.label':           'Coming Soon',
        'soon.fiat-vault.title':'Fiat Vault',
        'soon.fiat-vault.body': 'Fiat custody and B2B receivables. Backend schema is ready (payment_intent / ramp_transaction); service-side logic sits in the P1 Cashier module.',
        'soon.payouts.title':   'Payouts',
        'soon.payouts.body':    'Merchant withdrawals. The backend already enforces 4-eyes approval at the schema level; the console is on the P1 list.',
        'soon.conversion.title':'Conversion',
        'soon.conversion.body': 'On-chain swaps and bridge transfers. The BridgeProvider port is defined; real adapters are P0 → P1.',
        'soon.approvals.title': 'Approvals',
        'soon.approvals.body':  'Multi-party approvals and rules. Audit log + outbox tables exist; flows are queued for P1.',
        'soon.reports.title':   'Report Center',
        'soon.reports.body':    'Reconciliation and settlement reporting. Lights up once Cashier + Settlement are wired end-to-end.',
        'soon.members.title':   'Members',
        'soon.members.body':    'Members, roles and permissions. Only the demo user is enabled today; MFA/TOTP columns are reserved in schema.',
        'soon.page.eyebrow':    'OBITA · ',
        'soon.page.sub':        'This module is on the backend roadmap; the UI is not built yet. The note below summarises status.',

        'inbox.title':         'Inbox',
        'inbox.unread':        'Unread',
        'inbox.empty':         'No messages.',
        'inbox.msg.compliance.title': 'Action required · Compliance',
        'inbox.msg.compliance.body':  'Please upload your latest business registration documents — required by HK SFC TCSP renewal.',
        'inbox.msg.deposit.title':    'Deposit credited',
        'inbox.msg.deposit.body':     '500 USDC-POLYGON has been credited to your AVAILABLE balance after 12 confirmations.',
        'inbox.msg.statement.title':  'Monthly statement available',
        'inbox.msg.statement.body':   'Your March account statement is ready to download from Report Center.',
        'inbox.msg.welcome.title':    'Welcome to Obita',
        'inbox.msg.welcome.body':     "Read the quick-start guide to wire up your first deposit address and merchant order.",
        'inbox.time.2min':            '2 min ago',
        'inbox.time.10min':           '10 min ago',
        'inbox.time.1day':            '1 day ago',
        'inbox.time.3day':            '3 days ago',

        'profile.my':       'My profile',
        'profile.security': 'Security',
        'profile.docs':     'API docs (Swagger UI)',
        'profile.toast.my-profile': 'Profile editor lands in P1.',
        'profile.toast.security':   'Security center (MFA / sessions) is on the P1 roadmap.',

        'members.sub':             'All accounts that can sign in to this merchant. The backend already enforces role-based authorization on every controller.',
        'members.invite':          '+ Invite member',
        'members.invite.toast':    'Invite flow lands with the Members API in P1.',
        'members.kpi.total':       'Total members',
        'members.kpi.total.meta':  'Active and pending combined',
        'members.kpi.active':      'Active',
        'members.kpi.active.meta': 'Currently sign-in capable',
        'members.kpi.mfa':         'MFA enrolled',
        'members.kpi.mfa.meta':    'Members with TOTP active',
        'members.kpi.pending':     'Pending invites',
        'members.kpi.pending.meta':'Invitations not yet accepted',
        'members.section':         'Members & Roles',
        'members.col.name':        'Name',
        'members.col.email':       'Email',
        'members.col.role':        'Role',
        'members.col.mfa':         'MFA',
        'members.col.last':        'Last login',
        'members.col.status':      'Status',
        'members.note':            'Mock data — backend role tables exist (app_user / member_role / role_permission); the Members controller + invite flow ship in P1.',

        'approvals.sub':           'A unified queue across compliance, payouts, address allowlist, and member changes. Severity bars match legacy design.md §3.5.',
        'approvals.kpi.total':     'In Queue',
        'approvals.kpi.total.meta':'Across categories',
        'approvals.kpi.urgent':    'Urgent',
        'approvals.kpi.urgent.meta':'Compliance / regulatory',
        'approvals.kpi.action':    'Action',
        'approvals.kpi.action.meta':'Payout / withdrawal',
        'approvals.kpi.info':      'Awareness',
        'approvals.kpi.info.meta': 'Address book / member',
        'approvals.section':       'Open Approvals',
        'approvals.cat.compliance':'Compliance',
        'approvals.cat.payout':    'Payout',
        'approvals.cat.address':   'Address Book',
        'approvals.cat.member':    'Member',
        'approvals.row.compliance.title':'Annual KYC refresh required',
        'approvals.row.compliance.meta': 'Reg: HK SFC TCSP · due 2026-05-15',
        'approvals.row.payout.title':    'Withdraw 500 USDT-TRC20 → TQrY5xMK…RQ1CZ',
        'approvals.row.payout.meta':     'WDR-002 · 4-eyes required by policy',
        'approvals.row.address.title':   'Add 0xA0b86991…06eB48 to allowlist (ETH)',
        'approvals.row.address.meta':    'Submitted by ops · 24h cool-down enforced',
        'approvals.row.member.title':    'Promote audit@obita.demo to OPERATOR',
        'approvals.row.member.meta':     'Role change requested',
        'approvals.requested.by':       'Requested by',
        'approvals.action.approve':     'Approve',
        'approvals.action.reject':      'Reject',
        'approvals.action.toast':       'Approval flow lands in P1 — wired through audit_log + outbox.',
        'approvals.note':               'Mock — the audit_log + outbox_event tables are ready; real approval routing arrives in P1.',

        'conversion.sub':         'On-chain stablecoin swaps and cross-chain bridge transfers. Real adapters wire to the BridgeProvider port (P0 → P1).',
        'conversion.from':        'From',
        'conversion.to':          'To',
        'conversion.amount':      'Amount',
        'conversion.rate':        'Rate (mock)',
        'conversion.receive':     'You receive (est.)',
        'conversion.fee':         'Fee',
        'conversion.same':        'Choose two different assets.',
        'conversion.submit':      'Submit conversion',
        'conversion.toast':       'Conversion routing arrives with the BridgeProvider impl (P1).',
        'conversion.section':     'Convert',
        'conversion.history':     'Recent conversions',
        'conversion.col.pair':    'Pair',
        'conversion.col.amount':  'Amount',
        'conversion.col.received':'Received',
        'conversion.col.rate':    'Rate',
        'conversion.col.when':    'When',
        'conversion.col.status':  'Status',

        'reports.sub':            'Statements, reconciliation, and audit exports. The OpenAPI spec is live below — every implemented endpoint is browsable.',
        'reports.section.available': 'Available reports',
        'reports.card.balance.tag':  'BALANCES',
        'reports.card.balance.title':'Balance snapshot · CSV',
        'reports.card.balance.sub':  'Account-level balances at a point in time. Stablecoin and (future) fiat.',
        'reports.card.orders.tag':   'ORDERS',
        'reports.card.orders.title': 'Order activity · CSV',
        'reports.card.orders.sub':   'Lifecycle export of merchant orders with timestamps and settlement amounts.',
        'reports.card.ledger.tag':   'LEDGER',
        'reports.card.ledger.title': 'Ledger export · CSV',
        'reports.card.ledger.sub':   'Per-tx ledger_entry feed with debit / credit pairs and balance_after.',
        'reports.card.cta':          'Download · soon',
        'reports.toast':             'Report export lands once the backend exposes /v1/reports (P1).',

        'payouts.sub':           'Merchant withdrawals. The backend schema already enforces 4-eyes approval, address allowlist, and 24h cool-down.',
        'payouts.new':           '+ New withdrawal',
        'payouts.toast':         'Withdrawal flow lands with the Payouts controller (P1).',
        'payouts.kpi.all':       'All requests',
        'payouts.kpi.all.meta':  'Total count',
        'payouts.kpi.pending':   'Pending approval',
        'payouts.kpi.pending.meta':'Awaiting 2nd eye',
        'payouts.kpi.approved':  'Approved / broadcast',
        'payouts.kpi.approved.meta':'Sent to chain adapter',
        'payouts.kpi.confirmed': 'Confirmed',
        'payouts.kpi.confirmed.meta':'On-chain settled',
        'payouts.section':       'Withdrawal requests',
        'payouts.col.id':        'ID',
        'payouts.col.chain':     'Chain',
        'payouts.col.to':        'To',
        'payouts.col.amount':    'Amount',
        'payouts.col.status':    'Status',
        'payouts.col.when':      'Requested',

        'common.cancel':       'Cancel',
        'common.confirm':      'Confirm',
        'common.loading':      'Loading…',
        'common.error.head':   'Failed to load',
        'common.session.expired':'Session expired — please sign in again.',
    },
    zh: {
        'login.eyebrow':   '登录 · Backend Demo',
        'login.title':     '商户操作台',
        'login.sub':       '登录以连接后端 API。本页验证四个核心流程：账户余额 · 订单 · 入金扫块 · 资金分录。',
        'login.merchant':  '商户代码',
        'login.username':  '用户名',
        'login.password':  '密码',
        'login.submit':    '登录 →',
        'login.api':       'API',
        'login.brand.eyebrow':  'Vol.04 · Web2 + Web3 资金管理',
        'login.brand.headline.l1': '让',
        'login.brand.headline.l2': '支付',
        'login.brand.headline.em': '无国界。',
        'login.brand.sub': '多链稳定币托管 · 法币出入金 · 复式分录账本 — 为商户司库台而生。',
        'login.brand.live':'在线 · 本地环境',
        'login.brand.seal':'TCSP · MSO · 持牌运营',

        'header.merchant': '商户',
        'header.refresh':  '刷新',
        'header.notif':    '通知',
        'header.lang':     '语言',
        'header.logout':   '退出登录',

        'nav.section.vaults':   '资产保险柜',
        'nav.section.flow':     '资金流',
        'nav.section.ops':      '运营',
        'nav.section.account':  '账户',
        'nav.overview':   '总览',
        'nav.vault':      '稳定币保险柜',
        'nav.fiat-vault': '法币保险柜',
        'nav.orders':     '订单',
        'nav.payouts':    '出款',
        'nav.conversion': '兑换',
        'nav.ledger':     '账本',
        'nav.approvals':  '审批',
        'nav.reports':    '报表中心',
        'nav.members':    '成员',
        'nav.soon':       '待开发',
        'sidebar.backend':'后端',

        'page.overview.eyebrow': 'OBITA · 商户总览',
        'page.overview.title':   '商户操作台 · 总览',
        'page.overview.sub':     '当日入金 / 订单 / 结算的快速一览。所有数字直接来自后端账本。',
        'overview.kpi.available':'可用余额合计',
        'overview.kpi.available.meta': '稳定币合计 · USDC + USDT 等的 AVAILABLE 之和。',
        'overview.kpi.pending':  '入金待确认',
        'overview.kpi.pending.meta':  '链上等待确认的入金。',
        'overview.kpi.open':     '进行中订单',
        'overview.kpi.open.meta':     '待支付 + 已支付 + 退款中。',
        'overview.kpi.settled':  '已结算（近 10 单）',
        'overview.kpi.settled.meta':  '最近 10 笔中已结算的数量。',
        'overview.balances.title':    '余额 · 各资产',
        'overview.balances.action':   '进入保险柜 →',
        'overview.recent.title':      '最近订单',
        'overview.recent.action':     '全部订单 →',
        'overview.recent.empty.head': '还没有订单',
        'overview.recent.empty.body': '点击右上角「+ 新建订单」创建第一笔。',

        'page.vault.eyebrow': 'TCSP · 稳定币保险柜',
        'page.vault.title':   '稳定币保险柜',
        'page.vault.sub':     '申请一个链上入金地址。扫块器在 ~10 秒内识别 mock-bank 注入的 credit，并在 12 个确认（~30 秒）后把余额从 PENDING 移到 AVAILABLE。',
        'vault.balances.title':  '余额 · 一览',
        'vault.address.title':   '地址簿 · 入金地址',
        'vault.address.empty':   '尚未申请任何地址',
        'vault.address.empty.sub':'使用下方表单申请。',
        'vault.provision.title': '申请新地址',
        'vault.provision.chain':  '链',
        'vault.provision.purpose':'用途',
        'vault.provision.label':  '标签',
        'vault.provision.submit': '申请地址',
        'vault.mock.title':      '模拟入金 · 注入链上 credit',
        'vault.mock.note.lead':  '本卡仅用于本地演示。',
        'vault.mock.note':       ' 后端 POST /mock-bank/credit 将一笔合成 credit 推给链适配器；扫块器在 ~10 秒识别 → 写 deposit + 1/2 分录；~30 秒后到 12 confirmations → CREDITED + 3/4 分录。',
        'vault.mock.to':         '目标地址',
        'vault.mock.asset':      '资产',
        'vault.mock.amount':     '金额',
        'vault.mock.submit':     '注入 mock-bank credit',
        'vault.mock.toast':      '已注入 mock-bank credit · scanner 处理中…',
        'vault.address.copy':    '复制地址',
        'vault.address.copied':  '已复制到剪贴板',
        'vault.address.provisioned':'地址已申请',
        'vault.address.history': '历史',

        'wallet.history.title':       '钱包流水',
        'wallet.history.empty':       '该地址暂无链上活动。',
        'wallet.history.deposit.confirmed': '入金到账 · 计入 AVAILABLE',
        'wallet.history.row.topup':   '链上充值',
        'wallet.history.row.settle':  '订单结算 · 出账',
        'wallet.history.tag.live':    '实时',
        'wallet.history.tag.deposit': '入金',
        'wallet.history.tag.settle':  '结算',

        'page.orders.eyebrow': 'MSO · 商户订单',
        'page.orders.title':   '商户订单',
        'page.orders.sub':     '生命周期：CREATED → PENDING_PAYMENT → PAID → SETTLED → REFUNDING → REFUNDED。每个状态切换都通过 @Idempotent 后端控制器并入分录。',
        'orders.new':          '+ 新建订单',
        'orders.kpi.all':      '全部订单',
        'orders.kpi.all.meta': '总数',
        'orders.kpi.open':     '进行中',
        'orders.kpi.open.meta':'待支付 / 已支付 / 退款中',
        'orders.kpi.settled':  '已结算',
        'orders.kpi.settled.meta':'已到 SETTLED',
        'orders.kpi.refunds':  '退款',
        'orders.kpi.refunds.meta':'退款中 / 已退款',
        'orders.table.title':  '订单列表',
        'orders.col.order':    '订单',
        'orders.col.quote':    '报价',
        'orders.col.settle':   '结算',
        'orders.col.channel':  '通道',
        'orders.col.status':   '状态',
        'orders.col.time':     '时间',
        'orders.col.actions':  '操作',
        'orders.empty.head':   '还没有订单',
        'orders.empty.body':   '点击「+ 新建订单」创建第一笔。',
        'orders.action.markPaid': '标记已付',
        'orders.action.settle':   '结算',
        'orders.action.refund':   '退款',
        'orders.action.cancel':   '取消',
        'orders.toast.markPaid':  '订单已标记为已支付',
        'orders.toast.settle':    '结算完成 · 已入分录',
        'orders.toast.cancel':    '订单已取消',
        'orders.toast.refund':    '退款完成 · 已入分录',
        'orders.modal.title':     '新建订单',
        'orders.modal.no':        '商户订单号',
        'orders.modal.quote':     '报价币种',
        'orders.modal.amount':    '金额',
        'orders.modal.settleAsset':'结算币种',
        'orders.modal.channel':   '支付通道',
        'orders.modal.desc':      '描述',
        'orders.modal.desc.placeholder':'可选',
        'orders.modal.cancel':    '取消',
        'orders.modal.create':    '创建订单',
        'orders.modal.toast':     '订单已创建 (PENDING_PAYMENT)',
        'orders.refund.prompt':   '退款金额',
        'orders.cancel.prompt':   '取消原因（可选）',
        'orders.detail.title':    '订单详情',
        'orders.detail.section.info':   '订单信息',
        'orders.detail.section.events': '事件流水',
        'orders.detail.field.id':       '订单 ID',
        'orders.detail.field.no':       '商户订单号',
        'orders.detail.field.status':   '状态',
        'orders.detail.field.quote':    '报价',
        'orders.detail.field.settle':   '结算',
        'orders.detail.field.channel':  '通道',
        'orders.detail.field.expires':  '过期时间',
        'orders.detail.field.created':  '创建时间',
        'orders.detail.field.updated':  '更新时间',
        'orders.detail.field.desc':     '描述',
        'orders.detail.action.view':    '详情',

        'page.ledger.eyebrow': 'OBITA · 账本快照',
        'page.ledger.title':   '分录流水 · 余额快照',
        'page.ledger.sub':     '当前面板显示各账户最新 balance_after。完整的 per-tx 借贷流水接口（GET /v1/accounts/{id}/entries）在 P1 路线图。',
        'ledger.section':      '账户余额',
        'ledger.col.no':       '#',
        'ledger.col.asset':    '资产',
        'ledger.col.type':     '账户类型',
        'ledger.col.balance':  '当前余额',
        'ledger.col.note':     '说明',
        'ledger.row.note':     'snapshot · balance_after',
        'ledger.note.lead':    '提示：',
        'ledger.note.body':    ' 完整 happy-path 8 条分录可直接在 PG 查询：',
        'ledger.note.body2':   ' — 一笔 deposit + order settle + refund 形成借贷成对的 4 段；负的 PLATFORM SETTLEMENT 表示链上托管资产，详见 03-DOMAIN_MODEL.md §4。',

        'soon.label':           '即将上线',
        'soon.fiat-vault.title':'法币保险柜',
        'soon.fiat-vault.body': '法币托管与对公收付。后端 schema 已就位（payment_intent / ramp_transaction），服务端逻辑在 P1 Cashier 模块。',
        'soon.payouts.title':   '出款',
        'soon.payouts.body':    '商户出款 / 提现 (Withdrawal) 流程。后端 schema 已带 4-eyes 审批，前端控制台为 P1 待办。',
        'soon.conversion.title':'兑换',
        'soon.conversion.body': '链上代币兑换与跨链桥接。BridgeProvider 端口已定义，真实接入位于 P0 → P1。',
        'soon.approvals.title': '审批',
        'soon.approvals.body':  '多人审批与规则。审计表 / outbox 已规划，UI 与流程在 P1 队列。',
        'soon.reports.title':   '报表中心',
        'soon.reports.body':    '对账与结算报告。等 Cashier + Settlement 联通后接入。',
        'soon.members.title':   '成员',
        'soon.members.body':    '成员、角色、权限。当前仅 demo 用户启用；MFA/TOTP 已留 schema 列。',
        'soon.page.eyebrow':    'OBITA · ',
        'soon.page.sub':        '该模块在后端路线图中已规划，UI 暂未实现。下方为占位说明。',

        'inbox.title':         '收件箱',
        'inbox.unread':        '未读',
        'inbox.empty':         '暂无消息。',
        'inbox.msg.compliance.title': '待处理 · 合规',
        'inbox.msg.compliance.body':  '请上传最新的营业执照文件 —— 香港 SFC TCSP 续期所需。',
        'inbox.msg.deposit.title':    '入金已到账',
        'inbox.msg.deposit.body':     '500 USDC-POLYGON 已在 12 个确认后到账，余额已计入 AVAILABLE。',
        'inbox.msg.statement.title':  '月度账单已生成',
        'inbox.msg.statement.body':   '3 月账单可在 Report Center 下载。',
        'inbox.msg.welcome.title':    '欢迎使用 Obita',
        'inbox.msg.welcome.body':     '请阅读快速指南，配置第一个入金地址并创建商户订单。',
        'inbox.time.2min':            '2 分钟前',
        'inbox.time.10min':           '10 分钟前',
        'inbox.time.1day':            '1 天前',
        'inbox.time.3day':            '3 天前',

        'profile.my':       '个人资料',
        'profile.security': '安全设置',
        'profile.docs':     'API 文档 (Swagger UI)',
        'profile.toast.my-profile': '个人资料编辑在 P1 上线。',
        'profile.toast.security':   '安全中心（MFA / 会话）在 P1 路线。',

        'members.sub':             '可登录该商户的所有账户。后端已对每个控制器强制基于角色的鉴权。',
        'members.invite':          '+ 邀请成员',
        'members.invite.toast':    '邀请流程随 Members API 在 P1 上线。',
        'members.kpi.total':       '成员总数',
        'members.kpi.total.meta':  '激活与待邀请之和',
        'members.kpi.active':      '激活',
        'members.kpi.active.meta': '可登录账户',
        'members.kpi.mfa':         '已启用 MFA',
        'members.kpi.mfa.meta':    '已绑定 TOTP',
        'members.kpi.pending':     '待接受邀请',
        'members.kpi.pending.meta':'邀请尚未接受',
        'members.section':         '成员与角色',
        'members.col.name':        '姓名',
        'members.col.email':       '邮箱',
        'members.col.role':        '角色',
        'members.col.mfa':         'MFA',
        'members.col.last':        '上次登录',
        'members.col.status':      '状态',
        'members.note':            'Mock 数据 —— 后端角色表已就位（app_user / member_role / role_permission），Members 控制器与邀请流在 P1 上线。',

        'approvals.sub':           '跨合规、出款、地址簿、成员变更的统一审批队列。严重度条对照 design.md §3.5。',
        'approvals.kpi.total':     '队列中',
        'approvals.kpi.total.meta':'各类合计',
        'approvals.kpi.urgent':    '紧急',
        'approvals.kpi.urgent.meta':'合规 / 监管',
        'approvals.kpi.action':    '待处理',
        'approvals.kpi.action.meta':'出款 / 提现',
        'approvals.kpi.info':      '一般',
        'approvals.kpi.info.meta': '地址簿 / 成员',
        'approvals.section':       '待处理审批',
        'approvals.cat.compliance':'合规',
        'approvals.cat.payout':    '出款',
        'approvals.cat.address':   '地址簿',
        'approvals.cat.member':    '成员',
        'approvals.row.compliance.title':'年度 KYC 复核',
        'approvals.row.compliance.meta': '法规：HK SFC TCSP · 截止 2026-05-15',
        'approvals.row.payout.title':    '提现 500 USDT-TRC20 → TQrY5xMK…RQ1CZ',
        'approvals.row.payout.meta':     'WDR-002 · 政策要求 4-eyes',
        'approvals.row.address.title':   '将 0xA0b86991…06eB48 加入允许名单 (ETH)',
        'approvals.row.address.meta':    'ops 提交 · 强制 24 小时冷却',
        'approvals.row.member.title':    '将 audit@obita.demo 提升为 OPERATOR',
        'approvals.row.member.meta':     '角色变更请求',
        'approvals.requested.by':       '提交人',
        'approvals.action.approve':     '通过',
        'approvals.action.reject':      '驳回',
        'approvals.action.toast':       '审批流随 audit_log + outbox 在 P1 上线。',
        'approvals.note':               'Mock —— audit_log 与 outbox_event 已就位，真实审批路由在 P1。',

        'conversion.sub':         '链上稳定币兑换与跨链桥接。真实适配器接入 BridgeProvider 端口（P0 → P1）。',
        'conversion.from':        '从',
        'conversion.to':          '到',
        'conversion.amount':      '金额',
        'conversion.rate':        '汇率（mock）',
        'conversion.receive':     '预计到账',
        'conversion.fee':         '手续费',
        'conversion.same':        '请选择两种不同资产。',
        'conversion.submit':      '发起兑换',
        'conversion.toast':       '兑换路由随 BridgeProvider 实现（P1）。',
        'conversion.section':     '兑换',
        'conversion.history':     '最近兑换',
        'conversion.col.pair':    '币对',
        'conversion.col.amount':  '金额',
        'conversion.col.received':'到账',
        'conversion.col.rate':    '汇率',
        'conversion.col.when':    '时间',
        'conversion.col.status':  '状态',

        'reports.sub':            '账单、对账与审计导出。下方为后端 OpenAPI 直达链接 —— 已实现的端点全部可浏览。',
        'reports.section.available': '可用报表',
        'reports.card.balance.tag':  '余额',
        'reports.card.balance.title':'余额快照 · CSV',
        'reports.card.balance.sub':  '某时刻的账户级余额；含稳定币与（未来）法币。',
        'reports.card.orders.tag':   '订单',
        'reports.card.orders.title': '订单活动 · CSV',
        'reports.card.orders.sub':   '商户订单生命周期导出，含时间戳与结算金额。',
        'reports.card.ledger.tag':   '账本',
        'reports.card.ledger.title': '账本导出 · CSV',
        'reports.card.ledger.sub':   '逐笔 ledger_entry，含借贷成对与 balance_after。',
        'reports.card.cta':          '下载 · 即将上线',
        'reports.toast':             '报表导出随后端 /v1/reports 上线（P1）。',

        'payouts.sub':           '商户提现。后端 schema 已强制 4-eyes 审批、地址允许名单、24 小时冷却。',
        'payouts.new':           '+ 新建提现',
        'payouts.toast':         '提现流随 Payouts 控制器上线（P1）。',
        'payouts.kpi.all':       '全部请求',
        'payouts.kpi.all.meta':  '总数',
        'payouts.kpi.pending':   '待审批',
        'payouts.kpi.pending.meta':'等待第二人审批',
        'payouts.kpi.approved':  '已审批 / 已广播',
        'payouts.kpi.approved.meta':'已发链上适配器',
        'payouts.kpi.confirmed': '已确认',
        'payouts.kpi.confirmed.meta':'链上结算',
        'payouts.section':       '提现请求',
        'payouts.col.id':        '编号',
        'payouts.col.chain':     '链',
        'payouts.col.to':        '收款地址',
        'payouts.col.amount':    '金额',
        'payouts.col.status':    '状态',
        'payouts.col.when':      '提交时间',

        'common.cancel':       '取消',
        'common.confirm':      '确认',
        'common.loading':      '加载中…',
        'common.error.head':   '加载失败',
        'common.session.expired':'登录已过期，请重新登录。',
    },
};
